version: "3.6"
services: 
    app_backend:
        build:
            context: ./app
        image: "mpp:${LAB}"
        depends_on: 
            - postgres
        restart: always
        ports:
            - "3001:3000"
        volumes:
            - "/tmp/uploads/${LAB}:/app/uploads"
        environment: 
            DB_HOST: "postgres"
        command: "node build/index.js"
        container_name: "app_backend_${LAB}"
    postgres:
        image: postgres:12
        volumes: 
            - "postgres_data:/var/lib/postgresql/data"
            - "./postgres/init:/docker-entrypoint-initdb.d"
        environment:
            PGDATA: "/var/lib/postgresql/data/lab${LAB}"
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "db_spp"
        container_name: "mpp_postgres_${LAB}"

volumes: 
    postgres_data: