version: "3.6"
services: 
    node:
        build:
            context: ./app
        image: "mpp:${LAB}"
        depends_on: 
            - postgres
        restart: always
        ports:
            - "3000:3000"
        container_name: "mpp_node_${LAB}"
    postgres:
        image: postgres:12
        volumes: 
            - "postgres_data_${LAB}:/var/lib/postgresql/data"
            - "./postgres/init:/docker-entrypoint-initdb.d"
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: db_spp
        container_name: "mpp_postgres_${LAB}"

volumes: 
    - "postgres_data_${LAB}"