CREATE TABLE IF NOT EXISTS 'USER' (
    USER_ID SERIAL,
    EMAIL VARCHAR(255) NOT NULL,
    'PASSWORD' VARCHAR(255) NOT NULL,

    PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID SERIAL,
    TASK_TEXT VARCHAR(255) NOT NULL,
    TASK_STATUS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY INTEGER NOT NULL,
    ESTIMATED_END_AT DATE NOT NULL,
    FILE_ID INTEGER,

    PRIMARY KEY(TASK_ID),
    FOREIGN KEY(CREATED_BY) REFERENCES 'USER' (USER_ID)
);

CREATE TABLE IF NOT EXISTS TASK_FILE (
    FILE_ID SERIAL,
    TASK_ID INTEGER,
    FILE_NAME VARCHAR(255) NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,

    PRIMARY KEY(FILE_ID),
    FOREIGN KEY(TASK_ID) REFERENCES TASK (TASK_ID),
    FOREIGN KEY(CREATED_BY) REFERENCES 'USER' (USER_ID)
);

INSERT INTO 'USER' VALUES (
    -1,
    '',
    ''
);

INSERT INTO TASK VALUES (
    -1,
    'dummy task',
    '',
    NOW(),
    CURRENT_DATE,
    NULL,
    -1
);