export interface BaseTask {
    task_id?: string,
    task_text?: string,
    estimated_end_at?: string,
    file_id?: string
}

// Task, received from DB or generated by backend 
export interface RawTask extends BaseTask {
    task_status?: string,
    created_at?: string
}

// Task, formatted for presentation on client
export interface OutputTask extends BaseTask {
    task_status?: {
        text: string;
        value: string;
    };
    deadline?: boolean;
}

// Task, received from client
export interface InputTask extends BaseTask {
    task_status?: string;
    att_file?: File;
}

export interface Errors {
    text_short?: boolean,
    text_long?: boolean,
    estimated_end_at?: boolean,
    status_present?: boolean
}    